### ISSUE TITLE
Too large for storage?

### ISSUE THREAD

**Issue by appatalks** [appatalks/chatgpt-html#53]
```js
options.js:347 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'messages' exceeded the quota.
    at sendToNative (https://eva.hoshisato.com/core/js/options.js:347:18)
    at reader.onloadend (https://eva.hoshisato.com/core/js/options.js:324:11)
```

**Comment by appatalks** [comment]
I believe this is related: 

> [storage.local](https://developer.chrome.com/docs/extensions/reference/api/storage#property-local)
Data is stored locally and cleared when the extension is removed. The storage limit is 10 MB (5 MB in Chrome 113 and earlier), but can be increased by requesting the "unlimitedStorage" permission. We recommend using storage.local to store larger amounts of data.

- https://developer.chrome.com/docs/extensions/reference/api/storage#property-local

**Comment by appatalks** [comment]
Actually it seems that is just for `extensions`. 5MB is the suggested limit from googling. 

Will ponder on this.

**Comment by appatalks** [comment]
Anyway, have to design a new storage system for ```o1``` and future proof for ```o3``` models. 
And Google has been up to _things_, I need to relook into.

#### Ideas

- `Positronic` Matrix deployment - I'm **very** close to this.

**Comment by appatalks** [comment]
Move to #66
